clc;
clear;
xp=[0 0.5 1.0 1.5 1.8 2.0];
yp=2*sin(exp(xp))+exp(-xp);
  x=0:0.01:2;
  y=2*sin(exp(x))+exp(-x);
yl=interp1(xp,yp,x,'linear');
  figure('Position',[150 500 560 420]);
  plot(xp,yp,'ok',x,y,'--k',x,yl,'-k');
  grid on; xlabel('x'); ylabel('y');
  legend('точки','функция','лин.инт.',0);
n=length(xp);
c=polyfit(xp,yp,n);
yc=polyval(c,x);
  figure('Position',[700 500 560 420]);
  plot(xp,yp,'ok',x,y,'--k',x,yc,'-k');
  grid on; xlabel('x'); ylabel('y');
  legend('точки','функция','полином',0);
ys=interp1(xp,yp,x,'spline');
  figure('Position',[400 50 560 420]);
  plot(xp,yp,'ok',x,y,'--k',x,ys,'-k');
  grid on; xlabel('x'); ylabel('y');
  legend('точки','функция','сплайн',0);
